name: Test jdkFile
on: [push]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [macos-latest]
        version: [15.0.0]
        java-package: [jdk]
        provider: [jdkFile]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: get archive
      run: wget url":"https://cdn.azul.com/zulu/bin/zulu15.27.17-ca-fx-jdk15.0.0-macosx_x64.tar.gz

    - uses: dmitry-shibanov/setup-java@add-support-for-jdkfile
      with:
        java-version: ${{ matrix.version }}
        distribution: ${{ matrix.provider }}
        java-package: ${{ matrix.java-package }}
        jdkfile: zulu15.27.17-ca-fx-jdk15.0.0-macosx_x64.tar.gz
    - name: Java version
      shell: pwsh
      run: java -version
    - uses: dmitry-shibanov/setup-java@add-support-for-jdkfile
      with:
        java-version: ${{ matrix.version }}
        distribution: ${{ matrix.provider }}
        java-package: ${{ matrix.java-package }}
        jdkFile: zulu15.27.17-ca-fx-jdk15.0.0-macosx_x64.tar.gz
    - name: Java version
      shell: pwsh
      run: java -version
