
name: Test pypy
on: [push]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-18.04, macos-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check pypy default
      shell: pwsh
      continue-on-error: true
      run: |
        if ($IsWindows){
          pypy3 --version
        } else {
          pypy3 --version
        }

    - uses: dmitry-shibanov/setup-python@v-dmshib/add-support-for-semver-pypy
      with:
        pypy-version: pypy3.6-v7.3.2
    - name: PyPy version
      shell: pwsh
      run: |
        # ls "C:\hostedtoolcache\windows\PyPy\3.7\x64"
        if($IsWindows) {
          pypy3 --version
          python --version
        } else {
          python --version
          pypy --version
          python3 --version
        }
