
name: Test pypy
on: [push]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check tar
      run: |
        tar --help
        tar --version
        curl https://downloads.python.org/pypy/pypy3.7-v7.3.3-linux64.tar.bz2
        sudo tar -xjf pypy3.7-v7.3.3-linux64.tar.bz2 2> /dev/null
        ls
    - name: Check pypy default
      shell: pwsh
      continue-on-error: true
      run: |
        if ($IsWindows){
          pypy --version
        } else {
          pypy --version
        }

    - name: check dir
      shell: pwsh
      run: |
          if ($IsWindows) {
            $Dest = "C:/" 
            $Path = "hostedtoolcache/windows"
            $ToolsDirectory = $Dest + $Path
            $toolcachePath = Join-Path $ToolsDirectory "PyPy"
            ls -R $toolcachePath
          } elseif ($IsLinux) {
            ls -R /opt/hostedtoolcache/PyPy
          } else {
            $toolcachePath = Join-Path $env:HOME "hostedtoolcache" "PyPy"
            ls -R $toolcachePath
          }
      continue-on-error: true
    - uses: dmitry-shibanov/setup-python@v-dmshib/add-support-for-pypy
      with:
        python-version: 3.7
        pypy-version: 7.3.3
    - name: PyPy version
      run: |
        # ls "C:\hostedtoolcache\windows\PyPy\3.7\x64"
        pypy3 --version
