
name: Test pypy
on: [push]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-18.04, macos-latest, windows-latest]
        pypy: ['pypy-3.b', 'pypy-3.6-v7.3.3', 'pypy-3.6-v7.3.2', 'pypy-2-v7.3.3','pypy-3.7-v7.3.x', 'pypy-3.6-v7.3.x', 'pypy-3.x-v7.3.x', 'pypy-3.7-v7.x', 'pypy-3.x-v7.x', 'pypy-3.6-v7.3.x', 'pypy-3.6-v7.x', 'pypy-3.6', 'pypy-3', 'pypy-2', 'pypy-3.6-vx', 'pypy-3.7-vx', 'pypy-3.x-vx', 'pypy-2.7-vx', 'pypy-2-vx', 'pypy-3.6-7.5.5', 'pypy-3.6-nightly', 'pypy-3-nightly']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: PyPy version
      shell: pwsh
      run: |
        if($IsWindows) {
          ls C:\hostedtoolcache\windows\PyPy\3.6.12\x86\bin
        }
    - uses: dmitry-shibanov/setup-python@v-dmshib/prepare-add-pypy-installation
      with:
        python-version: ${{ matrix.pypy }}
    - name: PyPy version
      shell: pwsh
      run: |
        if($IsWindows) {
          python --version
        } else {
          python --version
        }
    - name: Run simple code
      run: |
        python -m pip install --ignore-installed pip
        python -c 'import math; print(math.factorial(5))'
