
name: Test pypy
on: [push]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-18.04, macos-latest, windows-latest]
        pypy: ['pypy3.7-v7.3.3', 'pypy3.6-v7.3.3', 'pypy3.7-v7.3.x', 'pypy3.6-v7.3.x', 'pypy3.x-v7.3.x', 'pypy3.7-v7.x', 'pypy3.x-v7.x', 'pypy2.7-v7.3.3', 'pypy2.7-v7.3.2', 'pypy3.7-nightly']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: dmitry-shibanov/setup-python@v-dmshib/add-support-for-semver-nightly
      with:
        pypy-version: ${{ matrix.pypy }}
    - name: PyPy version
      shell: pwsh
      run: |
        if($IsWindows) {
          pypy3 --version
          python --version
        } else {
          python --version
          pypy --version
          python3 --version
        }
