
name: Test pypy extra cases
on: [push]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-18.04, macos-latest, windows-latest, ubuntu-16.04, ubuntu-20.04, windows-2016]
        pypy: ['pypy-2.7', 'pypy-3.6', 'pypy-3.7', 'pypy-2.7-nightly', 'pypy-3.6-nightly', 'pypy-3.7-nightly']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: dmitry-shibanov/setup-python@v-dmshib/fix-pypy-inst-python
      with:
        python-version: ${{ matrix.pypy }}
    - name: PyPy version
      shell: pwsh
      run: python --version
    - name: Run simple code
      run: |
        python -c 'import math; print(math.factorial(5))'
