name: Test setup-node caching
on: [push]
jobs:
  run:
    name: Node test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-18.04, macos-latest, windows-latest]
        version: [ '12.x', '14.x', '16.x' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: dmitry-shibanov/setup-node@add-caching
      with:
        node-version: ${{ matrix.version }}
        cache: npm
        key: ${{ runner.os }}-node1-${{ matrix.version }}-${{ hashFiles('**/package-lock.json') }}
    - name: Node version
      shell: pwsh
      run: node --version
    - name: Npm version
      shell: pwsh
      run: npm --version
    - name: Ls current directory
      shell: pwsh
      run: ls
    - name: Install dependencies
      run: npm install
