name: Test java
on: [push]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-18.04, macos-latest, windows-latest]
        version: [ '8' ]
        java-package: ['jdk', 'jre']
        provider: ["adoptOpenJdk", "zulu"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.version }}
        distribution: ${{ matrix.provider }}
        java-package: ${{ matrix.java-package }}
        check-latest: true
    - name: Java version
      shell: pwsh
      run: java -version
   
