name: Test java
on: [push]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-18.04, macos-latest, windows-latest]
        version: [ '1.11.x', '1.12', '13.x', '11.0.x', '1.8.x', '1.8', '8.x', 'x', '7.x' ]
        java-package: ['jdk', 'jre']
        provider: ["adoptOpenJdk", "zulu"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: dmitry-shibanov/setup-java@start-work-providers-feature
      with:
        java-version: ${{ matrix.version }}
        distribution: ${{ matrix.provider }}
        java-package: ${{ matrix.java-package }}
    - name: Java version
      shell: pwsh
      run: java -version
    - uses: dmitry-shibanov/setup-java@start-work-providers-feature
      with:
        java-version: ${{ matrix.version }}
        distribution: ${{ matrix.provider }}
        java-package: ${{ matrix.java-package }}
    - name: Java version
      shell: pwsh
      run: java -version

